version: '3.8'

services:
  mongodb:
    image: mongo:latest
    container_name: mongodb
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: user
      MONGO_INITDB_ROOT_PASSWORD: pass
    volumes:
      - mongodemo:/data/db
  
  remote-csv-data:
    image: remote-csv-image
    container_name: remote-csv
    ports:
      - "145:145"

volumes:
  mongodemo:
